modLoader="kotlinforforge"
loaderVersion="[4.3,)"
license = "${mod_license}"
issueTrackerURL="https://github.com/rerurate/ae2_1_type_infinity_cell/issues"

[[mixins]]
config = "ae2_1_type_infinity_cell.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL="https://github.com/rerurate514/ae2_1_type_infinity_cell"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "ae2"
mandatory = true
versionRange = "[15.4.0,)"
ordering = "AFTER"
side = "BOTH"